### ISSUE TITLE
I don't see anything

### ISSUE THREAD

**Issue by Falling10fruit** [cooldudes24/pygame1#1]
Is it normal or am I supposed to see something?

**Comment by cooldudes24** [comment]
I'm not sure. I don't usually use Github that much; I mostly either use the Desktop version or I contribute to other people's work. But I made this a long time ago.

**Comment by Falling10fruit** [comment]
Oh okay, so should the issue be closed?

**Comment by cooldudes24** [comment]
That sounds good.

**Comment by Falling10fruit** [comment]
Okay, I'll close it.
